# Generated by Django 4.1 on 2022-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("denominated_asset", models.CharField(max_length=100)),
                ("vault_proxy", models.CharField(max_length=100)),
                ("comptroller_proxy", models.CharField(max_length=100)),
            ],
        ),
    ]
