# Generated by Django 4.1 on 2022-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="creator",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="comptroller_proxy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="denominated_asset",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="vault_proxy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
