# Generated by Django 4.1 on 2022-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0002_fund_creator_alter_fund_comptroller_proxy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="comptroller_proxy",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="vault_proxy",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
