# Generated by Django 4.1 on 2022-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0003_alter_fund_comptroller_proxy_alter_fund_vault_proxy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="id",
        ),
        migrations.AlterField(
            model_name="fund",
            name="comptroller_proxy",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
