# Generated by Django 4.1 on 2022-09-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0005_asset"),
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_time", models.DurationField()),
                (
                    "denominated_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denominated_asset",
                        to="fund.asset",
                        verbose_name="對價資產",
                    ),
                ),
                (
                    "target_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_asset",
                        to="fund.asset",
                        verbose_name="資產",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
    ]
