# Generated by Django 4.1 on 2022-09-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_liquiditymanagement_delete_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquiditymanagement",
            name="ftx_pair_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
