# Generated by Django 4.1 on 2022-09-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_liquiditymanagement_ftx_pair_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liquiditymanagement",
            name="round_time",
        ),
    ]
