# Generated by Django 4.1 on 2022-09-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_remove_liquiditymanagement_round_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquiditymanagement",
            name="round_time",
            field=models.DurationField(null=True),
        ),
    ]
