# Generated by Django 4.1 on 2022-09-02 06:49

from django.db import migrations
import management.fields


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_liquiditymanagement_round_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquiditymanagement",
            name="round_time",
            field=management.fields.CustomDurationField(null=True),
        ),
    ]
