"""
This type stub file was generated by pyright.
"""

import os
import platform
import tempfile
from gunicorn import util

PLATFORM = ...
IS_CYGWIN = ...
class WorkerTmp:
    def __init__(self, cfg) -> None:
        ...
    
    def notify(self): # -> None:
        ...
    
    def last_update(self): # -> float:
        ...
    
    def fileno(self): # -> int:
        ...
    
    def close(self): # -> None:
        ...
    


