"""
This type stub file was generated by pyright.
"""

from typing import Any
from os import urandom

__all__ = ['new', 'get_random_bytes']
class _UrandomRNG:
    def read(self, n: int) -> bytes:
        ...
    
    def flush(self) -> None:
        ...
    
    def reinit(self) -> None:
        ...
    
    def close(self) -> None:
        ...
    


def new(*args: Any, **kwargs: Any) -> _UrandomRNG:
    ...

def atfork() -> None:
    ...

get_random_bytes = ...
