"""
This type stub file was generated by pyright.
"""

import asyncio
import socket
from contextlib import suppress
from typing import Optional

"""Helper methods to tune a TCP connection"""
__all__ = ("tcp_keepalive", "tcp_nodelay")
if hasattr(socket, "SO_KEEPALIVE"):
    def tcp_keepalive(transport: asyncio.Transport) -> None:
        ...
    
else:
    def tcp_keepalive(transport: asyncio.Transport) -> None:
        ...
    
def tcp_nodelay(transport: asyncio.Transport, value: bool) -> None:
    ...

