"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, TYPE_CHECKING
from eth_utils.curried import apply_formatter_at_index, apply_formatter_if, apply_formatters_to_dict, is_null, is_string
from eth_utils.toolz import complement, compose, curry, dissoc
from hexbytes import HexBytes
from web3._utils.formatters import hex_to_integer
from web3._utils.rpc_abi import RPC
from web3.exceptions import ExtraDataLengthError, ValidationError
from web3.middleware.formatting import construct_web3_formatting_middleware
from web3.types import FormattersDict, TxParams
from web3 import Web3

if TYPE_CHECKING:
    ...
MAX_EXTRADATA_LENGTH = ...
is_not_null = ...
to_integer_if_hex = ...
@curry
def validate_chain_id(web3: Web3, chain_id: int) -> int:
    ...

def check_extradata_length(val: Any) -> Any:
    ...

def transaction_normalizer(transaction: TxParams) -> TxParams:
    ...

def transaction_param_validator(web3: Web3) -> Callable[..., Any]:
    ...

BLOCK_VALIDATORS = ...
block_validator = ...
@curry
def chain_id_validator(web3: Web3) -> Callable[..., Any]:
    ...

def build_validators_with_web3(w3: Web3) -> FormattersDict:
    ...

validation_middleware = construct_web3_formatting_middleware(build_validators_with_web3)
