"""
This type stub file was generated by pyright.
"""

import hashlib
import hmac
import unicodedata
from typing import Union
from eth_keys import keys
from eth_utils import ValidationError
from hexbytes import HexBytes

PBKDF2_ROUNDS = ...
SECP256K1_N = ...
def normalize_string(txt: Union[str, bytes]) -> str:
    ...

def sha256(data: bytes) -> bytes:
    ...

def hmac_sha512(chain_code: bytes, data: bytes) -> bytes:
    """
    As specified by RFC4231 - https://tools.ietf.org/html/rfc4231 .
    """
    ...

def pbkdf2_hmac_sha512(passcode: str, salt: str) -> bytes:
    ...

def ec_point(pkey: bytes) -> bytes:
    """
    Compute `point(p)`, where `point` is ecdsa point multiplication.

    Note: Result is ecdsa public key serialized to compressed form
    """
    ...

