"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from typing import Optional
from eth_utils import big_endian_to_int
from eth_keys.datatypes import BaseSignature, NonRecoverableSignature, PrivateKey, PublicKey, Signature
from eth_keys.exceptions import BadSignature
from eth_keys.validation import validate_uncompressed_public_key_bytes
from eth_keys.utils import der
from eth_keys.utils.numeric import coerce_low_s
from .base import BaseECCBackend

def is_coincurve_available() -> bool:
    ...

class CoinCurveECCBackend(BaseECCBackend):
    def __init__(self) -> None:
        ...
    
    def ecdsa_sign(self, msg_hash: bytes, private_key: PrivateKey) -> Signature:
        ...
    
    def ecdsa_sign_non_recoverable(self, msg_hash: bytes, private_key: PrivateKey) -> NonRecoverableSignature:
        ...
    
    def ecdsa_verify(self, msg_hash: bytes, signature: BaseSignature, public_key: PublicKey) -> bool:
        ...
    
    def ecdsa_recover(self, msg_hash: bytes, signature: Signature) -> PublicKey:
        ...
    
    def private_key_to_public_key(self, private_key: PrivateKey) -> PublicKey:
        ...
    
    def decompress_public_key_bytes(self, compressed_public_key_bytes: bytes) -> bytes:
        ...
    
    def compress_public_key_bytes(self, uncompressed_public_key_bytes: bytes) -> bytes:
        ...
    


