"""
This type stub file was generated by pyright.
"""

import importlib
import logging
import os
from eth_hash.abc import BackendAPI
from eth_hash.backends import SUPPORTED_BACKENDS

def auto_choose_backend() -> BackendAPI:
    ...

def get_backend_in_environment() -> str:
    ...

def load_backend(backend_name: str) -> BackendAPI:
    ...

def load_environment_backend(env_backend: str) -> BackendAPI:
    ...

def choose_available_backend() -> BackendAPI:
    ...

