"""
This type stub file was generated by pyright.
"""

import io
import sys
from gunicorn.http.errors import ChunkMissingTerminator, InvalidChunkSize, NoMoreData

class ChunkedReader:
    def __init__(self, req, unreader) -> None:
        ...
    
    def read(self, size): # -> bytes:
        ...
    
    def parse_trailers(self, unreader, data): # -> Literal[b''] | None:
        ...
    
    def parse_chunked(self, unreader): # -> Generator[bytes | Any | None, None, None]:
        ...
    
    def parse_chunk_size(self, unreader, data=...): # -> tuple[Literal[0], None] | tuple[int, bytes]:
        ...
    
    def get_data(self, unreader, buf): # -> None:
        ...
    


class LengthReader:
    def __init__(self, unreader, length) -> None:
        ...
    
    def read(self, size): # -> bytes:
        ...
    


class EOFReader:
    def __init__(self, unreader) -> None:
        ...
    
    def read(self, size): # -> bytes:
        ...
    


class Body:
    def __init__(self, reader) -> None:
        ...
    
    def __iter__(self): # -> Self@Body:
        ...
    
    def __next__(self): # -> bytes:
        ...
    
    next = ...
    def getsize(self, size): # -> int:
        ...
    
    def read(self, size=...): # -> bytes:
        ...
    
    def readline(self, size=...): # -> bytes:
        ...
    
    def readlines(self, size=...): # -> list:
        ...
    


