"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, ItemsView, List
from eth_typing import Address, HexStr
from ethpm.validation.package import validate_contract_name
from web3._utils.compat import TypedDict
from web3.eth import Contract

class Deployments:
    """
    Deployment object to access instances of
    deployed contracts belonging to a package.
    """
    def __init__(self, deployment_data: Dict[str, Dict[str, str]], contract_instances: Dict[str, Contract]) -> None:
        ...
    
    def __getitem__(self, key: str) -> Dict[str, str]:
        ...
    
    def __contains__(self, key: str) -> bool:
        ...
    
    def get(self, key: str) -> Dict[str, str]:
        ...
    
    def items(self) -> ItemsView[str, Dict[str, str]]:
        ...
    
    def values(self) -> List[Dict[str, str]]:
        ...
    
    def get_instance(self, contract_name: str) -> Contract:
        """
        Fetches a contract instance belonging to deployment
        after validating contract name.
        """
        ...
    


class DeploymentData(TypedDict):
    address: Address
    transaction: HexStr
    block: HexStr
    runtime_bytecode: Dict[str, Any]
    compiler: Dict[str, str]
    contractType: str
    ...


