"""
This type stub file was generated by pyright.
"""

import hashlib
import json
import uuid
from Crypto import Random
from Crypto.Cipher import AES
from Crypto.Protocol.KDF import scrypt
from Crypto.Util import Counter
from eth_keys import keys
from eth_utils import big_endian_to_int, decode_hex, encode_hex, int_to_big_endian, is_dict, is_string, keccak, remove_0x_prefix, to_dict

def encode_hex_no_prefix(value): # -> HexStr:
    ...

def load_keyfile(path_or_file_obj): # -> Any:
    ...

def create_keyfile_json(private_key, password, version=..., kdf=..., iterations=...): # -> dict[str, Any]:
    ...

def decode_keyfile_json(raw_keyfile_json, password): # -> bytes:
    ...

def extract_key_from_keyfile(path_or_file_obj, password): # -> bytes:
    ...

@to_dict
def normalize_keys(keyfile_json): # -> Generator[tuple, None, None]:
    ...

DKLEN = ...
SCRYPT_R = ...
SCRYPT_P = ...
def decrypt_aes_ctr(ciphertext, key, iv): # -> bytes:
    ...

def encrypt_aes_ctr(value, key, iv): # -> bytes:
    ...

def get_default_work_factor_for_kdf(kdf): # -> Literal[1000000, 262144]:
    ...

