"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from eth_keys.constants import IDENTITY_POINTS, SECPK1_A as A, SECPK1_N as N, SECPK1_P as P

def inv(a: int, n: int) -> int:
    ...

def to_jacobian(p: Tuple[int, int]) -> Tuple[int, int, int]:
    ...

def jacobian_double(p: Tuple[int, int, int]) -> Tuple[int, int, int]:
    ...

def jacobian_add(p: Tuple[int, int, int], q: Tuple[int, int, int]) -> Tuple[int, int, int]:
    ...

def from_jacobian(p: Tuple[int, int, int]) -> Tuple[int, int]:
    ...

def jacobian_multiply(a: Tuple[int, int, int], n: int) -> Tuple[int, int, int]:
    ...

def fast_multiply(a: Tuple[int, int], n: int) -> Tuple[int, int]:
    ...

def fast_add(a: Tuple[int, int], b: Tuple[int, int]) -> Tuple[int, int]:
    ...

def is_identity(p: Tuple[int, int, int]) -> bool:
    ...

