"""
This type stub file was generated by pyright.
"""

import importlib
from __future__ import absolute_import

LENGTH_PREFIXED_VAR_SIZE = ...
class NoneCodec:
    SIZE = ...
    IS_PATH = ...


CODEC_CACHE = ...
def codec_by_name(name): # -> Type[NoneCodec] | ModuleType:
    ...

