"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING, cast
from web3.types import BlockIdentifier, TxParams, Wei
from web3 import Web3
from web3.eth import AsyncEth

if TYPE_CHECKING:
    ...
async def get_block_gas_limit(web3_eth: AsyncEth, block_identifier: Optional[BlockIdentifier] = ...) -> Wei:
    ...

async def get_buffered_gas_estimate(web3: Web3, transaction: TxParams, gas_buffer: Wei = ...) -> Wei:
    ...

