"""
This type stub file was generated by pyright.
"""

import collections
import math
import operator
from typing import Iterable, Sequence, Tuple
from eth_typing import ChecksumAddress
from eth_utils import to_tuple
from eth_utils.toolz import curry, groupby, sliding_window
from hexbytes import HexBytes
from web3 import Web3
from web3._utils.math import percentile
from web3.exceptions import InsufficientData, ValidationError
from web3.types import BlockNumber, GasPriceStrategy, TxParams, Wei

MinerData = ...
Probability = ...
@curry
def construct_time_based_gas_price_strategy(max_wait_seconds: int, sample_size: int = ..., probability: int = ..., weighted: bool = ...) -> GasPriceStrategy:
    """
    A gas pricing strategy that uses recently mined block data to derive a gas
    price for which a transaction is likely to be mined within X seconds with
    probability P. If the weighted kwarg is True, more recent block
    times will be more heavily weighted.

    :param max_wait_seconds: The desired maximum number of seconds the
        transaction should take to mine.
    :param sample_size: The number of recent blocks to sample
    :param probability: An integer representation of the desired probability
        that the transaction will be mined within ``max_wait_seconds``.  0 means 0%
        and 100 means 100%.
    """
    ...

fast_gas_price_strategy = construct_time_based_gas_price_strategy(max_wait_seconds=60, sample_size=120)
medium_gas_price_strategy = construct_time_based_gas_price_strategy(max_wait_seconds=600, sample_size=120)
slow_gas_price_strategy = construct_time_based_gas_price_strategy(max_wait_seconds=60 * 60, sample_size=120)
glacial_gas_price_strategy = construct_time_based_gas_price_strategy(max_wait_seconds=24 * 60 * 60, sample_size=720)
