"""
This type stub file was generated by pyright.
"""

import io
import six
import varint
from . import exceptions
from .codecs import LENGTH_PREFIXED_VAR_SIZE, codec_by_name
from .protocols import protocol_with_code, protocol_with_name

def string_to_bytes(string): # -> bytes:
    ...

def bytes_to_string(buf): # -> str:
    ...

def size_for_addr(codec, buf_io): # -> int:
    ...

def string_iter(string): # -> Generator[tuple[Protocol, Type[NoneCodec] | ModuleType | Any, LiteralString | Any | None], None, None]:
    ...

def bytes_iter(buf): # -> Generator[tuple[int, Protocol, Type[NoneCodec] | ModuleType | Any, bytes], None, None]:
    ...

